-- https://neovim.io/doc/user/lua-guide.html#lua-guide-mappings

local utils = require("utils")
local is_available = utils.is_available
local map = utils.map

map.v("p",            'p:let @+=@0<CR>:let @"=@0<CR>') -- Don't copy the replaced text after pasting in visual mode
map.n("k", "v:count == 0 ? 'gk' : 'k'", { expr = true })
map.n("j", "v:count == 0 ? 'gj' : 'j'", { expr = true })

-- disable arrow keys
map.niv("<Up>",       '<CMD>echo "Use k to move!!"<CR>')
map.niv("<Down>",     '<CMD>echo "Use j to move!!"<CR>')
map.niv("<Left>",     '<CMD>echo "Use h to move!!"<CR>')
map.niv("<Right>",    '<CMD>echo "Use l to move!!"<CR>')

map.n("<Esc>",        "<CMD>nohlsearch<CR>")
map.nv("H",           "0",                      "Move to the beginning of the line")
map.nv("L",           "$",                      "Move to the end of the line")
map.n("J",            "<C-d>zz",                "Move down half page")
map.n("K",            "<C-u>zz",                "Move up half page")
map.n("n",            "nzz",                    "Center next match")
map.n("N",            "Nzz",                    "Center previous match")
map.n("]b",           ":bn<CR>",                "Next buffer")
map.n("[b",           ":bp<CR>",                "Previous buffer")
map.n("<C-w>b",       ":bd<CR>",                "Delete buffer")
map.n("]t",           ":tabnext<CR>",           "Next tab")
map.n("[t",           ":tabprevious<CR>",       "Previous tab")
map.v("<Leader>/",    [["hy:%s/<C-r>h/<C-r>h]], "Search and replace selected text")
map.n("<Leader>/",    ":%s/<C-r><C-w>/",        "Search and replace word under cursor")
map.n("vv",           "V",                      "Select whole line")
map.n("V",            "v$",                     "Select to end of line")
map.n("vaf",          "ggVG",                   "Select whole file")
map.n("yaf",          "ggVGy",                  "Yank whole file")
map.nv("<Leader>y",   '"+y',                    "Yank to system clipboard")
map.n("<C-Up>",       ":hori res +1<CR>",       "Increase Window Height")
map.n("<C-Down>",     ":hori res -2<CR>",       "Decrease Window Height")
map.n("<C-Right>",    ":vert res +2<CR>",       "Increase Window Width")
map.n("<C-Left>",     ":vert res -2<CR>",       "Decrease Window Width")
map.n("<C-s>",        ":w<CR>",                 "Save file")
map.i("<C-s>",        "<Esc>:w<CR>a",           "Save file")
map.n("<C-q>",        ":q<CR>",                 "Quit")
map.n("<C-Q>",        ":qall<CR>",              "Quit All")
map.n("<A-j>",        ":m+1<CR>",               "Move line down")
map.n("<A-k>",        ":m-2<CR>",               "Move line up")
map.v("<A-j>",        ":m'>+1<CR>gv=gv",        "Move line down")
map.v("<A-k>",        ":m'<-2<CR>gv=gv",        "Move line up")
map.n("<A-a>",        "J",                      "Join lines")
map.v("<A-h>",        "<gv",                    "Indent Left")
map.v("<A-l>",        ">gv",                    "Indent Right")
map.n("<A-h>",        "<<",                     "Indent Left")
map.n("<A-l>",        ">>",                     "Indent Right")
map.n("<A-z>",        utils.toggle_wrap,        "Toggle Wrap")
map.n("Q",            "@q", "Macro q")
map.n("[e",           vim.diagnostic.goto_prev, "Previous diagnostic",  "nvim-lspconfig")
map.n("]e",           vim.diagnostic.goto_next, "Next diagnostic",      "nvim-lspconfig")
map.n("<Leader>e",    ":Neotree toggle<CR>",    "Toggle file explorer", "neo-tree.nvim")
map.n("<Leader>e",    ":NvimTreeToggle<CR>",    "Toggle file explorer", "nvim-tree.lua")
map.n("<Leader>u",    vim.cmd.UndotreeToggle,   "Toggle undo tree",     "undotree")
